kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo
  labels:
    app: mongo
    part-of: mangatagger
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
    keel.sh/match-tag: true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      part-of: mangatagger
  template:
    metadata:
      labels:
        app: mongo
        part-of: mangatagger
    spec:
      serviceAccountName: mangatagger
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - name: mongo
          containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mangatagger
              key: MANGA_TAGGER_DB_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mangatagger
              key: MANGA_TAGGER_DB_PASSWORD
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mangatagger
              key: MANGA_TAGGER_DB_NAME
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 64Mi
        volumeMounts:
        - name: mangatagger-secrets
          mountPath: "/mnt/vault"
          readOnly: true
      volumes:
      - name: mangatagger-secrets
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "mangatagger"
